export const PATH = {
  AUTH: '/',
  MAIN: '/home',
  EMAILAUTH: '/emailauth',
  SIGNUP: '/signup',
  SEARCH: '/search',
  REVIEW: '/place/:placeid/review',
  ADDPLACE: '/add',
  PLACELISTS: '/places',
  PLACEDETAIL: '/place/:placeid',
  MY: `/user/:userid`,
  MYEDIT: '/user/:userid/edit',
  REDIRECTION: '/auth/kakao/callback',
  NOTFOUND: '*',
};
