export const PATH = {
  AUTH: '/',
  MAIN: '/home',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SEARCH: '/search',
  REVIEW: '/place/:placeid/review',
  ADDPLACE: '/add',
  PLACELISTS: '/places',
  PLACEDETAIL: '/place/:placeid',
  MY: `/user`,
  MYEDIT: '/user/:userid/edit',
  LOGOUT: '/user/:userid/logout',
  REDIRECTION: '/auth/kakao/callback',
  NOTFOUND: '*',
};
